import { execSync } from 'child_process';
import { existsSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(__dirname, '..', '..');

export function run(cmd, options = {}) {
  console.log(`  $ ${cmd}`);
  return execSync(cmd, { cwd: ROOT, encoding: 'utf-8', timeout: 120000, ...options });
}

export function detectSupabaseCmd() {
  // 1. Check local node_modules/.bin (installed as devDep)
  const localBin = path.join(ROOT, 'node_modules', '.bin', 'supabase');
  const localBinCmd = process.platform === 'win32' ? localBin + '.cmd' : localBin;
  if (existsSync(localBinCmd)) {
    return 'npx supabase';
  }

  // 2. Check global install (Scoop on Windows, brew on Mac)
  try {
    execSync('supabase --version', { stdio: 'pipe', encoding: 'utf-8' });
    return 'supabase';
  } catch {}

  return null;
}

export function installSupabaseLocal() {
  console.log('→ Installing Supabase CLI as dev dependency...\n');
  run('npm install supabase --save-dev', { stdio: 'inherit', timeout: 120000 });
  const localBin = path.join(ROOT, 'node_modules', '.bin', 'supabase');
  const localBinCmd = process.platform === 'win32' ? localBin + '.cmd' : localBin;
  if (existsSync(localBinCmd)) {
    return 'npx supabase';
  }
  return null;
}

export function checkDocker() {
  try {
    execSync('docker info', { stdio: 'pipe', encoding: 'utf-8' });
    return true;
  } catch {
    return false;
  }
}

export async function ensureSupabase(supabaseCmd) {
  if (!existsSync(path.join(ROOT, 'supabase'))) {
    console.log('\n→ Initializing Supabase project...');
    run(`${supabaseCmd} init`);
  }

  let running = false;
  try {
    const out = execSync(`${supabaseCmd} status --output json`, { cwd: ROOT, encoding: 'utf-8' });
    const s = JSON.parse(out);
    running = !!s.api_url;
  } catch {}

  if (!running) {
    console.log('\n→ Starting Supabase (first Docker pull may take minutes)...\n');
    run(`${supabaseCmd} start`, { stdio: 'inherit', timeout: 300000 });
  } else {
    console.log('\n✓ Supabase already running');
  }

  const status = JSON.parse(run(`${supabaseCmd} status --output json`));

  if (!status.api_url || !status.anon_key) {
    throw new Error('Could not get Supabase credentials from local instance.');
  }

  console.log(`  API URL:    ${status.api_url}`);
  console.log(`  Studio:     ${status.studio_url}`);

  console.log('\n→ Applying schema.sql...');
  try {
    run(`${supabaseCmd} db execute --file schema.sql`, { stdio: 'inherit' });
  } catch {
    console.log('  (tables may already exist — continuing)');
  }

  writeFileSync(path.join(ROOT, '.env'), [
    '# Auto-generated by scripts/lib/supabase-local.mjs',
    `VITE_SUPABASE_URL="${status.api_url}"`,
    `VITE_SUPABASE_ANON_KEY="${status.anon_key}"`,
    'ISLOCAL="true"',
    '',
  ].join('\n'));

  return status;
}
